export interface NavItem {
  label: string
  path: string
  icon: string
}

export interface NavSection {
  title: string
  items: NavItem[]
}

export const navSections: NavSection[] = [
  {
    title: 'OVERVIEW',
    items: [
      { label: 'Home', path: '/', icon: 'ri-home-4-line' },
      { label: 'CyberSec Fundamentals', path: '/getting-started', icon: 'ri-rocket-line' },
      { label: 'Additional Information', path: '/additional-info', icon: 'ri-information-line' },
    ],
  },
  {
   title: 'CYBERSECURITY MODULES',
    items: [
      { label: 'Cybersecurity Overview', path: '/cybersecurity', icon: 'ri-shield-check-line' },

      { label: 'Cybersecurity Foundations', path: '/cybersecurity/foundations-security-mindset', icon: 'ri-book-line' },
      { label: 'Networking & OSI', path: '/cybersecurity/networking-osi-fundamentals', icon: 'ri-book-line' },
      { label: 'Cryptography Basics', path: '/cybersecurity/cryptography-basics', icon: 'ri-book-line' },
      { label: 'Authentication & Access Control', path: '/cybersecurity/authentication-authorization', icon: 'ri-book-line' },

      { label: 'Quiz 1', path: '/cybersecurity/quiz-1', icon: 'ri-questionnaire-line' },

      { label: 'Vulnerabilities & OWASP', path: '/cybersecurity/common-vulnerabilities-owasp', icon: 'ri-book-line' },
      { label: 'Malware & Threats', path: '/cybersecurity/malware-threat-landscape', icon: 'ri-book-line' },
      { label: 'Incident Response & Forensics', path: '/cybersecurity/incident-response-forensics', icon: 'ri-book-line' },
      { label: 'Security Operations (SOC)', path: '/cybersecurity/security-operations-soc', icon: 'ri-book-line' },

      { label: 'Quiz 2', path: '/cybersecurity/quiz-2', icon: 'ri-questionnaire-line' },

      { label: 'Penetration Testing', path: '/cybersecurity/pentesting-methodologies', icon: 'ri-book-line' },
      { label: 'Web App Security', path: '/cybersecurity/web-app-security', icon: 'ri-book-line' },
      { label: 'Wireless & Network Security', path: '/cybersecurity/wireless-network-security', icon: 'ri-book-line' },
      { label: 'Cloud & DevOps Security', path: '/cybersecurity/cloud-devops-security', icon: 'ri-book-line' },

      { label: 'Quiz 3', path: '/cybersecurity/quiz-3', icon: 'ri-questionnaire-line' },

      { label: 'Mobile & IoT Security', path: '/cybersecurity/mobile-iot-security', icon: 'ri-book-line' },
      { label: 'Social Engineering', path: '/cybersecurity/social-engineering', icon: 'ri-book-line' },
      { label: 'Encryption & Cryptanalysis', path: '/cybersecurity/encryption-cryptanalysis', icon: 'ri-book-line' },
      { label: 'Security Architecture', path: '/cybersecurity/security-architecture', icon: 'ri-book-line' },

      { label: 'Quiz 4', path: '/cybersecurity/quiz-4', icon: 'ri-questionnaire-line' },
      
      { label: 'Cybersecurity Law & Ethics', path: '/cybersecurity/compliance-legal-ethics', icon: 'ri-book-line' },
      { label: 'DevSecOps & Secure SDLC', path: '/cybersecurity/devsecops-secure-sdlc', icon: 'ri-book-line' },
      { label: 'Threat Intelligence', path: '/cybersecurity/threat-intelligence', icon: 'ri-book-line' },
      { label: 'Cybersecurity Careers', path: '/cybersecurity/career-paths-future', icon: 'ri-book-line' },
      
       { label: 'Final Exam', path: '/cybersecurity/final-exam', icon: 'ri-questionnaire-line' },
    ],
  },
  {
    title: 'WIRESHARK',
    items: [
      { label: 'Wireshark Overview', path: '/wireshark', icon: 'ri-shield-check-line' },
      { label: 'Capture Filters', path: '/wireshark/capture-filters', icon: 'ri-filter-3-line' },
      { label: 'Display Filters', path: '/wireshark/display-filters', icon: 'ri-search-line' },
      { label: 'Filter Builder', path: '/wireshark/filter-builder', icon: 'ri-tools-line' },
      { label: 'Protocol Analysis', path: '/wireshark/protocol-analysis', icon: 'ri-exchange-line' },
      { label: 'Advanced Features', path: '/wireshark/advanced-features', icon: 'ri-bar-chart-grouped-line' },
      { label: 'Command Line', path: '/wireshark/command-line', icon: 'ri-terminal-line' },
      { label: 'Troubleshooting', path: '/wireshark/troubleshooting', icon: 'ri-bug-line' },
      { label: 'Wireshark Quiz', path: '/wireshark/wireshark-quiz', icon: 'ri-questionnaire-line' },
      { label: 'Wireshark Lab', path: '/wireshark/wireshark-lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'NMAP',
    items: [
      { label: 'Nmap Overview', path: '/nmap', icon: 'ri-shield-check-line' },
      { label: 'Installation', path: '/nmap/installation', icon: 'ri-download-line' },
      { label: 'What is Nmap', path: '/nmap/what-is-nmap', icon: 'ri-information-line' },
      { label: 'How Nmap Works', path: '/nmap/how-it-works', icon: 'ri-settings-3-line' },
      { label: 'Scan Types', path: '/nmap/scan-types', icon: 'ri-radar-line' },
      { label: 'Port States', path: '/nmap/port-states', icon: 'ri-door-open-line' },
      { label: 'Timing Templates', path: '/nmap/timing', icon: 'ri-time-line' },
      { label: 'Common Flags', path: '/nmap/flags', icon: 'ri-flag-line' },
      { label: 'NSE Scripts', path: '/nmap/nse-scripts', icon: 'ri-code-s-slash-line' },
      { label: 'Usage Examples', path: '/nmap/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/nmap/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/nmap/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'Nmap Quiz', path: '/nmap/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Nmap Lab', path: '/nmap/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'GOBUSTER',
    items: [
      { label: 'Gobuster Overview', path: '/gobuster', icon: 'ri-folder-open-line' },
      { label: 'Installation', path: '/gobuster/installation', icon: 'ri-download-line' },
      { label: 'Directory Bruteforce', path: '/gobuster/directory', icon: 'ri-folder-3-line' },
      { label: 'DNS Subdomain', path: '/gobuster/dns', icon: 'ri-earth-line' },
      { label: 'Virtual Hosts', path: '/gobuster/vhost', icon: 'ri-server-line' },
      { label: 'S3 Buckets', path: '/gobuster/s3', icon: 'ri-cloud-line' },
      { label: 'Fuzzing', path: '/gobuster/fuzz', icon: 'ri-bug-line' },
      { label: 'Common Flags', path: '/gobuster/flags', icon: 'ri-flag-line' },
      { label: 'Wordlists', path: '/gobuster/wordlists', icon: 'ri-file-list-3-line' },
      { label: 'Usage Examples', path: '/gobuster/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/gobuster/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/gobuster/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'Gobuster Quiz', path: '/gobuster/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Gobuster Lab', path: '/gobuster/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'JOHN THE RIPPER',
    items: [
      { label: 'John the Ripper Overview', path: '/john-the-ripper', icon: 'ri-lock-unlock-line' },
      { label: 'Installation', path: '/john-the-ripper/installation', icon: 'ri-download-line' },
      { label: 'Single Crack Mode', path: '/john-the-ripper/single-crack-mode', icon: 'ri-user-line' },
      { label: 'Wordlist Mode', path: '/john-the-ripper/wordlist-mode', icon: 'ri-file-list-3-line' },
      { label: 'Incremental Mode', path: '/john-the-ripper/incremental-mode', icon: 'ri-speed-line' },
      { label: 'External Mode', path: '/john-the-ripper/external-mode', icon: 'ri-code-s-slash-line' },
      { label: 'Hash Formats', path: '/john-the-ripper/hash-formats', icon: 'ri-database-2-line' },
      { label: 'Rules', path: '/john-the-ripper/rules', icon: 'ri-magic-line' },
      { label: 'Hash Extraction', path: '/john-the-ripper/hash-extraction', icon: 'ri-fingerprint-line' },
      { label: 'Command Builder', path: '/john-the-ripper/command-builder', icon: 'ri-tools-line' },
      { label: 'Examples', path: '/john-the-ripper/examples', icon: 'ri-file-list-line' },
      { label: 'Pro Tips', path: '/john-the-ripper/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'John the Ripper Quiz', path: '/john-the-ripper/quiz', icon: 'ri-questionnaire-line' },
      { label: 'John the Ripper Lab', path: '/john-the-ripper/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'BURP SUITE',
    items: [
      { label: 'Burp Suite Overview', path: '/burp-suite', icon: 'ri-bug-line' },
      { label: 'Installation & Setup', path: '/burp-suite/installation', icon: 'ri-download-line' },
      { label: 'Proxy', path: '/burp-suite/proxy', icon: 'ri-exchange-line' },
      { label: 'Repeater', path: '/burp-suite/repeater', icon: 'ri-repeat-line' },
      { label: 'Intruder', path: '/burp-suite/intruder', icon: 'ri-sword-line' },
      { label: 'Scanner', path: '/burp-suite/scanner', icon: 'ri-scan-line' },
      { label: 'Decoder', path: '/burp-suite/decoder', icon: 'ri-code-box-line' },
      { label: 'Comparer', path: '/burp-suite/comparer', icon: 'ri-arrow-left-right-line' },
      { label: 'Extensions', path: '/burp-suite/extensions', icon: 'ri-apps-line' },
      { label: 'Testing Workflow', path: '/burp-suite/workflow', icon: 'ri-road-map-line' },
      { label: 'Configuration Builder', path: '/burp-suite/command-builder', icon: 'ri-tools-line' },
      { label: 'Examples', path: '/burp-suite/examples', icon: 'ri-file-list-line' },
      { label: 'Pro Tips', path: '/burp-suite/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'Burp Suite Quiz', path: '/burp-suite/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Burp Suite Lab', path: '/burp-suite/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'SQLMAP',
    items: [
      { label: 'SQLMap Overview', path: '/sqlmap', icon: 'ri-database-2-line' },
      { label: 'Installation', path: '/sqlmap/installation', icon: 'ri-download-line' },
      { label: 'Injection Techniques', path: '/sqlmap/injection-techniques', icon: 'ri-code-s-slash-line' },
      { label: 'Tamper Scripts', path: '/sqlmap/tamper-scripts', icon: 'ri-shield-keyhole-line' },
      { label: 'Detection & Enumeration', path: '/sqlmap/detection', icon: 'ri-radar-line' },
      { label: 'Database Enumeration', path: '/sqlmap/database-enumeration', icon: 'ri-database-2-line' },
      { label: 'Data Extraction', path: '/sqlmap/data-extraction', icon: 'ri-download-cloud-line' },
      { label: 'OS Commands', path: '/sqlmap/os-commands', icon: 'ri-terminal-box-line' },
      { label: 'Common Flags', path: '/sqlmap/flags', icon: 'ri-flag-line' },
      { label: 'Usage Examples', path: '/sqlmap/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/sqlmap/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/sqlmap/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'SQLMap Quiz', path: '/sqlmap/quiz', icon: 'ri-questionnaire-line' },
      { label: 'SQLMap Lab', path: '/sqlmap/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'CLOUDSPLOIT',
    items: [
      { label: 'Cloudsploit Overview', path: '/cloudsploit', icon: 'ri-shield-keyhole-line' },
      { label: 'Installation', path: '/cloudsploit/installation', icon: 'ri-download-line' },
      { label: 'Configuration', path: '/cloudsploit/configuration', icon: 'ri-settings-3-line' },
      { label: 'Running Scans', path: '/cloudsploit/running-scans', icon: 'ri-play-line' },
      { label: 'AWS Scanners', path: '/cloudsploit/aws-scanners', icon: 'ri-amazon-line' },
      { label: 'Azure Scanners', path: '/cloudsploit/azure-scanners', icon: 'ri-microsoft-line' },
      { label: 'GCP Scanners', path: '/cloudsploit/gcp-scanners', icon: 'ri-google-line' },
      { label: 'Detector Reference', path: '/cloudsploit/detectors', icon: 'ri-search-eye-line' },
      { label: 'Command Flags', path: '/cloudsploit/command-flags', icon: 'ri-flag-line' },
      { label: 'Output Formats', path: '/cloudsploit/output-formats', icon: 'ri-file-list-3-line' },
      { label: 'Command Builder', path: '/cloudsploit/command-builder', icon: 'ri-tools-line' },
      { label: 'Examples', path: '/cloudsploit/examples', icon: 'ri-file-list-line' },
      { label: 'Pro Tips', path: '/cloudsploit/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'CI/CD Integration', path: '/cloudsploit/ci-cd', icon: 'ri-git-branch-line' },
      { label: 'Cloudsploit Quiz', path: '/cloudsploit/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Cloudsploit Lab', path: '/cloudsploit/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'SSLSCAN',
    items: [
      { label: 'SSLScan Overview', path: '/sslscan', icon: 'ri-shield-keyhole-line' },
      { label: 'Installation', path: '/sslscan/installation', icon: 'ri-download-line' },
      { label: 'Protocol Versions', path: '/sslscan/protocol-versions', icon: 'ri-stack-line' },
      { label: 'Cipher Suites', path: '/sslscan/cipher-suites', icon: 'ri-lock-line' },
      { label: 'Vulnerabilities', path: '/sslscan/vulnerabilities', icon: 'ri-alert-line' },
      { label: 'Common Flags', path: '/sslscan/flags', icon: 'ri-flag-line' },
      { label: 'Usage Examples', path: '/sslscan/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/sslscan/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/sslscan/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'SSLScan Quiz', path: '/sslscan/quiz', icon: 'ri-questionnaire-line' },
      { label: 'SSLScan Lab', path: '/sslscan/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'NETCAT',
    items: [
      { label: 'Netcat Overview', path: '/netcat', icon: 'ri-terminal-box-line' },
      { label: 'Installation', path: '/netcat/installation', icon: 'ri-download-line' },
      { label: 'Basic Usage', path: '/netcat/basic-usage', icon: 'ri-terminal-line' },
      { label: 'Connection Types', path: '/netcat/connection-types', icon: 'ri-link' },
      { label: 'File Transfer', path: '/netcat/file-transfer', icon: 'ri-file-copy-line' },
      { label: 'Port Scanning', path: '/netcat/port-scanning', icon: 'ri-target-line' },
      { label: 'Banner Grabbing', path: '/netcat/banner-grabbing', icon: 'ri-printer-line' },
      { label: 'Chat Application', path: '/netcat/chat', icon: 'ri-chat-3-line' },
      { label: 'Remote Shell', path: '/netcat/remote-shell', icon: 'ri-terminal-box-line' },
      { label: 'Flags & Options', path: '/netcat/flags', icon: 'ri-flag-line' },
      { label: 'Usage Examples', path: '/netcat/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/netcat/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/netcat/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'Netcat Quiz', path: '/netcat/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Netcat Lab', path: '/netcat/lab', icon: 'ri-flask-line' },
    ],
  },
  {
    title: 'METASPLOIT',
    items: [
      { label: 'Metasploit Overview', path: '/metasploit', icon: 'ri-fire-line' },
      { label: 'Installation', path: '/metasploit/installation', icon: 'ri-download-line' },
      { label: 'Module Types', path: '/metasploit/module-types', icon: 'ri-box-3-line' },
      { label: 'Essential Commands', path: '/metasploit/commands', icon: 'ri-terminal-line' },
      { label: 'Payloads', path: '/metasploit/payloads', icon: 'ri-rocket-line' },
      { label: 'Meterpreter', path: '/metasploit/meterpreter', icon: 'ri-terminal-box-line' },
      { label: 'Exploit Workflow', path: '/metasploit/workflow', icon: 'ri-road-map-line' },
      { label: 'Database', path: '/metasploit/database', icon: 'ri-database-2-line' },
      { label: 'Examples', path: '/metasploit/examples', icon: 'ri-file-list-line' },
      { label: 'Command Builder', path: '/metasploit/command-builder', icon: 'ri-tools-line' },
      { label: 'Pro Tips', path: '/metasploit/pro-tips', icon: 'ri-lightbulb-line' },
      { label: 'Metasploit Quiz', path: '/metasploit/quiz', icon: 'ri-questionnaire-line' },
      { label: 'Metasploit Lab', path: '/metasploit/lab', icon: 'ri-flask-line' },
    ],
  },
]